[workspace]
resolver = "2"

members = [
    "exchange",
    "exchange-algo",
    "exchange-core",
    "exchange-rt",
    "exchange-types",
]

[profile.release]
strip = true

[profile.bench]
debug = true
strip = false
