[package]
name = "orderbook-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
serde = { version = "~1.0", features = ["derive"], optional = true }
