[package]
name = "exchange-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
num = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
