[package]
name = "exchange-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
num = "0.4.1"
serde = { version = "~1.0", features = ["derive"], optional = true }
